[proxmox_nodes]
# Uncomment each node as it comes online and joins the cluster
sauron     ansible_host=172.21.13.16
witchking  ansible_host=172.21.13.17
khamul     ansible_host=172.21.13.18
gothmog    ansible_host=172.21.13.19
adunaphel  ansible_host=172.21.13.20
hoarmurath ansible_host=172.21.13.21
akhorahil  ansible_host=172.21.13.22
indur      ansible_host=172.21.13.23
dwar       ansible_host=172.21.13.24
ren        ansible_host=172.21.13.25
uvatha     ansible_host=172.21.13.26

[proxmox_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
